version: 2.0.{build}
image: Visual Studio 2019
build:
  verbosity: detailed
notifications:
  - provider: Email
    to:
      - email@muzzammil.xyz
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
